md Debug
cd Debug
md src
clang++ -DDEBUG -D_DEBUG -UNDEBUG -U_NDEBUG "-IC:\\workspace\\github\\llvm-project\\libcxx\\include" -O0 -emit-llvm -m64 -g3 -glldb -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -pedantic -Wall -c -fmessage-length=0 -Wextra -Wformat-security -Werror=format-security -std=c++17 -o "src\\Node.bc" "..\\..\\Node.cpp" 
clang++ -DDEBUG -D_DEBUG -UNDEBUG -U_NDEBUG "-IC:\\workspace\\github\\llvm-project\\libcxx\\include" -O0 -emit-llvm -m64 -g3 -glldb -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -pedantic -Wall -c -fmessage-length=0 -Wextra -Wformat-security -Werror=format-security -std=c++17 -o "src\\Graph.bc" "..\\..\\Graph.cpp" 
clang++ -DDEBUG -D_DEBUG -UNDEBUG -U_NDEBUG "-IC:\\workspace\\github\\llvm-project\\libcxx\\include" -O0 -emit-llvm -m64 -g3 -glldb -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -pedantic -Wall -c -fmessage-length=0 -Wextra -Wformat-security -Werror=format-security -std=c++17 -o "src\\main.bc" "..\\..\\main.cpp" 
clang++ -DDEBUG -D_DEBUG -UNDEBUG -U_NDEBUG "-IC:\\workspace\\github\\llvm-project\\libcxx\\include" -O0 -emit-llvm -m64 -g3 -glldb -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -pedantic -Wall -c -fmessage-length=0 -Wextra -Wformat-security -Werror=format-security -std=c++17 -o "src\\KingsPathApp.bc" "..\\..\\KingsPathApp.cpp" 
clang++ -DDEBUG -D_DEBUG -UNDEBUG -U_NDEBUG "-IC:\\workspace\\github\\llvm-project\\libcxx\\include" -O0 -emit-llvm -m64 -g3 -glldb -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -pedantic -Wall -c -fmessage-length=0 -Wextra -Wformat-security -Werror=format-security -std=c++17 -o "src\\Board.bc" "..\\..\\Board.cpp" 
clang++ "-LC:\\workspace\\github\\llvm-project\\build\\lib\\Debug" "-LC:\\LLVM-9\\lib" -Wl,/subsystem:console,/machine:x64,/debug:full -fuse-ld=lld -o KingsPath.exe "src\\Board.bc" "src\\Graph.bc" "src\\KingsPathApp.bc" "src\\Node.bc" "src\\main.bc" -lc++
